demo_olympus_quick_start();
//demo_olympus_test_async();
//demo_olympus_test_async_with_custom_global_callback_name();
//demo_olympus_test_async_with_user_feedback();
//demo_olympus_test_shared_variable();
//demo_olympus_test_shared_variable_from_custom_context();
//demo_olympus_test_bail();
//demo_olympus_test_explicit_dependencies();
//demo_olympus_test_dependency_chain()
//demo_olympus_hooks();
//demo_olympus_crash_recover();
//demo_olympus_ci_setup();